import { Router } from 'express';
import { protect, optionalAuth, authorize as A } from '../middleware/auth.js';
import * as auth from '../controllers/authController.js';
import * as c from '../controllers/courseController.js';
import * as admin from '../controllers/adminController.js';
import { learningPath, summary } from '../controllers/aiController.js';
import * as qz from '../controllers/quizController.js';
import * as misc from '../controllers/miscController.js';
import * as assignments from '../controllers/assignmentController.js';
import * as mentor from '../controllers/mentorController.js';
import * as platform from '../controllers/platformController.js';
const r = Router(), P = protect, INS = A('INSTRUCTOR', 'ADMIN');
r.post('/auth/register', auth.register); r.post('/auth/login', auth.login); r.post('/auth/logout', P, auth.logout); r.get('/auth/me', optionalAuth, auth.me);
r.get('/courses', c.list); r.get('/courses/mine', P, INS, c.mine); r.get('/courses/review-queue', P, A('REVIEWER', 'ADMIN'), c.queue);
r.get('/courses/:id', optionalAuth, c.get); r.post('/courses', P, INS, c.create); r.put('/courses/:id', P, INS, c.update);
r.post('/courses/:id/submit', P, INS, c.submit); r.post('/courses/:id/publish', P, INS, c.publish); r.post('/courses/:id/review', P, A('REVIEWER'), c.review);
r.post('/courses/:id/enroll', P, A('STUDENT'), c.enroll); r.post('/courses/:id/modules', P, INS, c.addModule); r.put('/courses/:id/modules/reorder', P, INS, c.reorderModules);
r.delete('/modules/:id', P, INS, c.deleteModule); r.put('/modules/:id', P, INS, c.updateModule); r.post('/modules/:id/lessons', P, INS, c.addLesson); r.delete('/lessons/:id', P, INS, c.deleteLesson); r.put('/lessons/:id', P, INS, c.updateLesson);
r.put('/modules/:id/lessons/reorder', P, INS, c.reorderLessons);
r.post('/lessons/:id/complete', P, A('STUDENT'), c.completeLesson); r.get('/enrollments/me', P, A('STUDENT'), c.myEnrollments);
r.get('/admin/users', P, A('ADMIN'), admin.users); r.patch('/admin/users/:id/role', P, A('ADMIN'), admin.setRole); r.patch('/admin/users/:id/active', P, A('ADMIN'), admin.setActive);
r.get('/ai/learning-path', P, A('STUDENT'), learningPath);
const S = A('STUDENT');
r.post('/courses/:id/quizzes', P, INS, qz.create); r.get('/courses/:id/quizzes/manage', P, INS, qz.manageList); r.get('/courses/:id/quizzes', P, S, qz.forCourse);
r.get('/quizzes/:id/manage', P, INS, qz.manageOne); r.put('/quizzes/:id', P, INS, qz.update); r.delete('/quizzes/:id', P, INS, qz.remove);
r.post('/quizzes/:id/questions', P, INS, qz.addQuestion); r.put('/questions/:id', P, INS, qz.updateQuestion); r.delete('/questions/:id', P, INS, qz.deleteQuestion);
r.post('/quizzes/:id/start', P, S, qz.start); r.get('/attempts/me', P, S, qz.myAttempts); r.post('/attempts/:id/submit', P, S, qz.submit); r.get('/attempts/:id', P, S, qz.getAttempt);
r.get('/students/me/summary', P, S, summary);
r.get('/notifications', P, misc.listNotes); r.patch('/notifications/read-all', P, misc.readAll); r.patch('/notifications/:id/read', P, misc.readNote);
r.get('/certificates/me', P, S, misc.myCerts); r.get('/certificates/verify/:certificateId', misc.verify);
r.get('/courses/:courseId/assignments', P, assignments.forCourse); r.post('/courses/:courseId/assignments', P, INS, assignments.create); r.put('/assignments/:id', P, INS, assignments.update); r.delete('/assignments/:id', P, INS, assignments.remove); r.get('/assignments/:id/submissions', P, INS, assignments.submissions); r.post('/assignments/:id/submit', P, S, assignments.submit); r.get('/assignments/submissions/me', P, S, assignments.mine); r.patch('/submissions/:id/grade', P, INS, assignments.grade);
r.get('/mentor/learners', P, A('MENTOR'), mentor.learners); r.get('/mentor/learners/:studentId', P, A('MENTOR'), mentor.learner); r.post('/mentor/learners/:studentId/notes', P, A('MENTOR'), mentor.addNote); r.get('/mentor/me', P, A('STUDENT'), mentor.myMentor); r.get('/mentoring-sessions', P, A('MENTOR', 'STUDENT'), mentor.sessions); r.post('/mentoring-sessions', P, A('MENTOR'), mentor.createSession); r.patch('/mentoring-sessions/:id', P, A('MENTOR'), mentor.updateSession);
r.get('/categories', platform.categories); r.post('/categories', P, A('ADMIN'), platform.createCategory); r.put('/categories/:id', P, A('ADMIN'), platform.updateCategory); r.delete('/categories/:id', P, A('ADMIN'), platform.deleteCategory); r.get('/analytics/instructor', P, INS, platform.instructorAnalytics); r.get('/analytics/admin', P, A('ADMIN'), platform.adminAnalytics); r.get('/reviews/history', P, A('REVIEWER', 'ADMIN'), platform.reviews); r.get('/audit-logs', P, A('ADMIN'), platform.auditLogs);
export default r;
