import 'dotenv/config';
import mongoose from 'mongoose';
import User from '../models/User.js';
import { Course, Module, Lesson } from '../models/Course.js';
import { Enrollment } from '../models/Learning.js';
import { CourseReview } from '../models/Learning.js';
import { Quiz, Question, QuizAttempt } from '../models/Quiz.js';
import Certificate from '../models/Certificate.js';
import Notification from '../models/Notification.js';
import { Assignment, AssignmentSubmission } from '../models/Assignment.js';
import { MentorAssignment, MentoringSession, MentoringNote } from '../models/Mentoring.js';
import { Category, AuditLog } from '../models/Admin.js';
await mongoose.connect(process.env.MONGO_URI);
await Promise.all([User, Course, Module, Lesson, Enrollment, CourseReview, Quiz, Question, QuizAttempt, Certificate, Notification, Assignment, AssignmentSubmission, MentorAssignment, MentoringSession, MentoringNote, Category, AuditLog].map((m) => m.deleteMany({})));
const mk = (name, email, role) => User.create({ name, email, role, password: 'Password123!' });
const [admin, ins, rev, stu, men] = [await mk('Admin User', 'admin@learnhub.demo', 'ADMIN'), await mk('Dr. Maya Patel', 'instructor@learnhub.demo', 'INSTRUCTOR'), await mk('Sam Rivera', 'reviewer@learnhub.demo', 'REVIEWER'), await mk('Alex Morgan', 'student@learnhub.demo', 'STUDENT'), await mk('Jordan Lee', 'mentor@learnhub.demo', 'MENTOR')];
await Category.insertMany([{ name: 'Web Development', description: 'Build for the web' }, { name: 'Data Structures', description: 'Core computing concepts' }, { name: 'AI & Machine Learning', description: 'Practical artificial intelligence' }]);
const build = async (title, category, level, status, mods) => {
  const c = await Course.create({ title, slug: title.toLowerCase().replace(/[^a-z0-9]+/g, '-'), description: `${title}: a hands-on course with modules, lessons and assessments.`, category, level, duration: '30h', instructor: ins._id, status, learningObjectives: ['Apply core concepts', 'Build a portfolio project'] });
  let n = 0; for (const [i, [mt, ls]] of mods.entries()) { const m = await Module.create({ title: mt, course: c._id, order: i }); for (const [j, t] of ls.entries()) await Lesson.create({ title: t, content: `Lesson notes for ${t}.`, duration: 15, order: j, isPreview: n++ === 0, module: m._id, course: c._id }); }
  return c;
};
const fs = await build('Full Stack Web Development', 'Web Development', 'Intermediate', 'PUBLISHED', [['Web Fundamentals', ['Introduction to Web Development', 'HTML Fundamentals', 'CSS Fundamentals', 'Responsive Design']], ['JavaScript', ['JavaScript Basics', 'Functions', 'Arrays and Objects', 'DOM Manipulation', 'Promises and Async/Await']], ['Backend Development', ['REST APIs', 'Authentication', 'Databases', 'Deployment']]]);
await build('Data Structures & Algorithms', 'Data Structures', 'Advanced', 'PUBLISHED', [['Foundations', ['Big-O', 'Arrays', 'Linked Lists']], ['Trees & Graphs', ['Trees', 'Graph Traversal', 'Recursion']]]);
await build('AI & Machine Learning Fundamentals', 'AI & Machine Learning', 'Beginner', 'SUBMITTED', [['Intro', ['What is ML', 'Supervised Learning']]]);
const ls = await Lesson.find({ course: fs._id }).sort('order');
await Enrollment.create({ user: stu._id, course: fs._id, completedLessons: ls.slice(0, 5).map((l) => l._id) });
const rc = await build('Responsive Web Design', 'Web Development', 'Beginner', 'PUBLISHED', [['Layouts', ['Flexbox', 'Grid']]]);
const done = new Date('2026-03-12');
await Enrollment.create({ user: stu._id, course: rc._id, completedLessons: (await Lesson.find({ course: rc._id })).map((l) => l._id), completedAt: done });
await Certificate.create({ certificateId: 'LH-2026-DEMO0001', user: stu._id, course: rc._id, studentName: stu.name, courseTitle: rc.title, instructorName: ins.name, completedAt: done });
const quiz = await Quiz.create({ course: fs._id, title: 'JavaScript & APIs Checkpoint', description: 'Promises, async/await, REST and the DOM.', timeLimitMin: 10, maxAttempts: 3, passPercent: 70, questionCount: 6 });
const QD = [['Which object represents the eventual result of an async operation?', ['Promise', 'Callback', 'Closure'], 0, 'Promises', 'A Promise represents a value that may resolve or reject later.'], ['Which method handles a rejected Promise?', ['.map', '.catch', '.push'], 1, 'Promises', '.catch handles rejections in a Promise chain.'], ['What does await do?', ['Blocks the page', 'Pauses the async function until the Promise settles', 'Creates a thread'], 1, 'Async/Await', 'await pauses only the async function.'], ['Which HTTP method replaces a resource?', ['POST', 'GET', 'PUT'], 2, 'REST APIs', 'PUT replaces; repeating it gives the same result.'], ['Which status code means Not Found?', ['200', '404', '500'], 1, 'REST APIs', '404 means the resource does not exist.'], ['Which method selects an element by id?', ['getElementById', 'getAll', 'findId'], 0, 'DOM', 'document.getElementById returns one element.'], ['Which CSS property creates a flex container?', ['display: flex', 'flex: none', 'float: flex'], 0, 'CSS', 'display: flex enables flexbox.']];
const qs = await Question.insertMany(QD.map(([text, options, correctIndex, concept, explanation]) => ({ quiz: quiz._id, text, options, correctIndex, concept, explanation })));
const pick6 = qs.slice(0, 6), wrong = new Set(['Promises', 'REST APIs']);
const answers = pick6.map((q) => ({ question: q._id, concept: q.concept, selected: wrong.has(q.concept) ? (q.correctIndex + 1) % 3 : q.correctIndex, correct: !wrong.has(q.concept) }));
const sc = answers.filter((a) => a.correct).length;
await QuizAttempt.create({ user: stu._id, quiz: quiz._id, course: fs._id, questionIds: pick6.map((q) => q._id), answers, attemptNumber: 1, score: sc, total: 6, percentage: Math.round((sc / 6) * 100), passed: false, concepts: [...new Set(answers.map((a) => a.concept))], weakConcepts: ['Promises', 'REST APIs'], status: 'SUBMITTED', startedAt: new Date(), submittedAt: new Date() });
const pendingAssignment = await Assignment.create({ title: 'REST API Design Brief', description: 'Explain your endpoint design.', instructions: 'Submit a concise design brief.', course: fs._id, dueDate: new Date(Date.now() + 7 * 864e5), maximumMarks: 100, createdBy: ins._id, requiredForCompletion: false });
const gradedAssignment = await Assignment.create({ title: 'Responsive Layout Exercise', description: 'Create a responsive page.', course: rc._id, dueDate: new Date('2026-03-01'), maximumMarks: 50, createdBy: ins._id });
await AssignmentSubmission.create({ student: stu._id, assignment: gradedAssignment._id, content: 'Completed responsive layout.', submittedAt: new Date('2026-02-25'), status: 'GRADED', marks: 45, feedback: 'Strong responsive structure.', gradedBy: ins._id, gradedAt: new Date('2026-02-27') });
await MentorAssignment.create({ mentor: men._id, student: stu._id }); await MentoringSession.create({ mentor: men._id, student: stu._id, scheduledFor: new Date(Date.now() + 3 * 864e5), topic: 'Promises and API support', notes: 'Review weak concepts before session.' }); await MentoringNote.create({ mentor: men._id, student: stu._id, note: 'Student is progressing well; focus on REST error handling.' });
await CourseReview.create({ course: fs._id, reviewer: rev._id, decision: 'APPROVED', comment: 'Learning structure is complete.' }); await AuditLog.insertMany([{ user: admin._id, action: 'REGISTERED', entityType: 'User', entityId: String(admin._id) }, { user: ins._id, action: 'COURSE_CREATED', entityType: 'Course', entityId: String(fs._id) }, { user: rev._id, action: 'COURSE_APPROVED', entityType: 'Course', entityId: String(fs._id) }, { user: ins._id, action: 'ASSIGNMENT_GRADED', entityType: 'AssignmentSubmission' }]);
await Notification.insertMany([[stu, 'QUIZ', 'You scored 33% on "JavaScript & APIs Checkpoint" (not passed).', '/results'], [stu, 'AI', 'New recommendation: review Promises, REST APIs.', '/ai'], [stu, 'CERTIFICATE', 'Your certificate for "Responsive Web Design" is ready.', '/certificates'], [ins, 'COURSE_APPROVED', 'Your course "Full Stack Web Development" was approved.', '/manage'], [rev, 'COURSE', 'New course awaiting review: AI & Machine Learning Fundamentals.', '/reviews']].map(([u, type, message, link]) => ({ user: u._id, type, message, link })));
console.log('Seeded. All demo accounts use password: Password123!'); await mongoose.disconnect();
