import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDown, ArrowUp, Pencil, Plus, Save, Send, Trash2 } from 'lucide-react';
import api, { msg } from '../services/api'; import { toast } from '../utils/toast'; import Assignments from './Assignments'; import Badge from '../components/Badge';
const blank={title:'',description:'',category:'',level:'Beginner',duration:'',learningObjectives:'',prerequisites:''};
const asPayload=f=>({...f,learningObjectives:f.learningObjectives.split('\n').map(x=>x.trim()).filter(Boolean),prerequisites:f.prerequisites.split('\n').map(x=>x.trim()).filter(Boolean)});
export default function Manage(){const[list,setList]=useState(null),[categories,setCategories]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[open,setOpen]=useState(null),[detail,setDetail]=useState(null),[show,setShow]=useState(false);
 const load=async()=>{try{setList((await api.get('/courses/mine')).data.courses);setCategories((await api.get('/categories')).data.categories.filter(c=>c.status==='ACTIVE'))}catch(e){toast(msg(e))}};useEffect(()=>{load()},[]);
 const view=async id=>{try{setOpen(id);const c=(await api.get(`/courses/${id}`)).data;const q=(await api.get(`/courses/${id}/quizzes/manage`)).data.quizzes;setDetail({...c,quizzes:q})}catch(e){toast(msg(e))}};
 const submit=async e=>{e.preventDefault();try{if(editing){await api.put(`/courses/${editing}`,asPayload(form));toast('Course saved; published changes return to draft review.')}else{await api.post('/courses',asPayload(form));toast('Draft created')}setForm(blank);setEditing(null);setShow(false);load()}catch(x){toast(msg(x))}};
 const move=async(type,id,index,arr,parent)=>{const copy=[...arr];const swap=index+(type==='up'?-1:1);if(swap<0||swap>=copy.length)return;[copy[index],copy[swap]]=[copy[swap],copy[index]];try{await api.put(parent?`/modules/${parent}/lessons/reorder`:`/courses/${open}/modules/reorder`,{ids:copy.map(x=>x._id)});await view(open)}catch(e){toast(msg(e))}};
 const act=async(fn,ok)=>{try{await fn();toast(ok);await load();if(open)await view(open)}catch(e){toast(msg(e))}};
 return <div className="space-y-4"><div className="flex justify-between"><h1 className="text-2xl font-bold">My courses</h1><button className="btn btn-p" onClick={()=>{setForm(blank);setEditing(null);setShow(!show)}}><Plus size={15}/>New course</button></div>
 {show&&<form className="card grid gap-3 md:grid-cols-2" onSubmit={submit}><h2 className="font-bold md:col-span-2">{editing?'Edit course':'Create a course'}</h2><label>Title<input className="input mt-1" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Level<select className="input mt-1" value={form.level} onChange={e=>setForm({...form,level:e.target.value})}>{['Beginner','Intermediate','Advanced'].map(x=><option key={x}>{x}</option>)}</select></label><label>Category<select className="input mt-1" value={form.category} required onChange={e=>setForm({...form,category:e.target.value})}><option value="">Choose category</option>{categories.map(c=><option key={c._id}>{c.name}</option>)}</select></label><label>Duration<input className="input mt-1" placeholder="e.g. 20 hours" value={form.duration} onChange={e=>setForm({...form,duration:e.target.value})}/></label><label className="md:col-span-2">Description<textarea className="input mt-1" required rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Learning objectives <span className="text-xs text-slate-500">(one per line)</span><textarea className="input mt-1" rows="3" value={form.learningObjectives} onChange={e=>setForm({...form,learningObjectives:e.target.value})}/></label><label>Prerequisites <span className="text-xs text-slate-500">(one per line)</span><textarea className="input mt-1" rows="3" value={form.prerequisites} onChange={e=>setForm({...form,prerequisites:e.target.value})}/></label><div className="flex gap-2 md:col-span-2"><button className="btn btn-p"><Save size={15}/>Save course</button><button type="button" className="btn" onClick={()=>setShow(false)}>Cancel</button></div></form>}
 {!list?<p>Loading…</p>:list.map(c=><div className="card" key={c._id}><div className="flex flex-wrap justify-between gap-2"><div><b>{c.title}</b> <Badge>{c.status}</Badge><p className="text-sm text-slate-500">{c.category} · {c.level}</p></div><div className="flex gap-2"><button className="btn" onClick={()=>{setForm({...c,learningObjectives:(c.learningObjectives||[]).join('\n'),prerequisites:(c.prerequisites||[]).join('\n')});setEditing(c._id);setShow(true)}}><Pencil size={14}/>Edit</button><button className="btn" onClick={()=>view(c._id)}>Content</button>{['DRAFT','CHANGES_REQUESTED'].includes(c.status)&&<button className="btn btn-p" onClick={()=>act(()=>api.post(`/courses/${c._id}/submit`),'Submitted for review')}><Send size={14}/>Submit</button>}</div></div>
 {open===c._id&&detail&&<div className="mt-4 space-y-3 border-t pt-3"><div className="flex justify-between"><b>Modules and lessons</b><button className="btn" onClick={()=>{const title=prompt('Module title');if(title)act(()=>api.post(`/courses/${c._id}/modules`,{title}),'Module added')}}>+ Module</button></div>{detail.modules.map((m,i)=><div className="rounded border p-3" key={m._id}><div className="flex justify-between"><b>{m.title}</b><span className="flex gap-1"><button className="btn" disabled={!i} onClick={()=>move('up',m._id,i,detail.modules)}><ArrowUp size={14}/></button><button className="btn" disabled={i===detail.modules.length-1} onClick={()=>move('down',m._id,i,detail.modules)}><ArrowDown size={14}/></button><button className="btn" onClick={()=>{const title=prompt('Lesson title');if(title)act(()=>api.post(`/modules/${m._id}/lessons`,{title,content:''}),'Lesson added')}}>+ Lesson</button><button className="btn" onClick={()=>confirm('Delete module and lessons?')&&act(()=>api.delete(`/modules/${m._id}`),'Module deleted')}><Trash2 size={14}/></button></span></div>{m.lessons.map((l,j)=><div className="ml-3 mt-2 flex justify-between text-sm" key={l._id}><span>{l.title}</span><span><button className="btn mr-1" disabled={!j} onClick={()=>move('up',l._id,j,m.lessons,m._id)}><ArrowUp size={13}/></button><button className="btn mr-1" disabled={j===m.lessons.length-1} onClick={()=>move('down',l._id,j,m.lessons,m._id)}><ArrowDown size={13}/></button><button className="btn" onClick={()=>confirm('Delete lesson?')&&act(()=>api.delete(`/lessons/${l._id}`),'Lesson deleted')}>Remove</button></span></div>)}</div>)}<div className="border-t pt-3"><b>Assignments</b><button className="btn ml-2" onClick={()=>{const title=prompt('Title');const dueDate=prompt('Due date (YYYY-MM-DD)');const maximumMarks=prompt('Maximum marks','100');if(title&&dueDate&&maximumMarks)act(()=>api.post(`/courses/${c._id}/assignments`,{title,dueDate,maximumMarks,instructions:''}),'Assignment created')}}>+ Assignment</button><Assignments courseId={c._id} instructor/></div><div className="border-t pt-3"><b>Quizzes</b>{detail.quizzes.map(q=><Link className="btn ml-2" key={q._id} to={`/manage/quiz/${q._id}`}>{q.title}</Link>)}</div></div>}</div>)}</div>}
