import { useEffect, useState } from 'react';
import api, { msg } from '../services/api';
import { toast } from '../utils/toast';
export default function Mentor() {
  const [learners, setLearners] = useState(null), [sessions, setSessions] = useState([]), [open, setOpen] = useState(null);
  const load = async () => { try { setLearners((await api.get('/mentor/learners')).data.learners); setSessions((await api.get('/mentoring-sessions')).data.sessions); } catch (e) { toast(msg(e)); } };
  useEffect(() => { load(); }, []); if (!learners) return <p>Loading…</p>;
  const schedule=async student=>{const topic=prompt('Session topic');const scheduledFor=prompt('Date and time (YYYY-MM-DDTHH:MM)');if(!topic||!scheduledFor)return;try{await api.post('/mentoring-sessions',{student,topic,scheduledFor});toast('Session scheduled');load()}catch(e){toast(msg(e))}};
  return <div className="space-y-4"><h1 className="text-2xl font-bold">Mentor dashboard</h1><div className="grid gap-3 md:grid-cols-2">{learners.map(x => <div className="card" key={x.learner._id}><b>{x.learner.name}</b><p className="text-sm">Quiz average: {x.quizAverage ?? '—'}%</p><p className="text-sm">Weak: {x.weakConcepts.map(c => c.concept).join(', ') || 'None'}</p><button className="btn mt-2" onClick={async () => setOpen((await api.get(`/mentor/learners/${x.learner._id}`)).data)}>Learner details</button><button className="btn mt-2 ml-2" onClick={()=>schedule(x.learner._id)}>Schedule session</button></div>)}</div><div className="card"><h2 className="font-bold">Upcoming sessions</h2>{sessions.map(s => <div className="flex justify-between border-t py-2 text-sm" key={s._id}><span>{new Date(s.scheduledFor).toLocaleString()} · {s.student.name} · {s.topic} · {s.status}</span>{s.status==='SCHEDULED'&&<span><button className="btn mr-1" onClick={async()=>{await api.patch(`/mentoring-sessions/${s._id}`,{status:'COMPLETED'});load()}}>Complete</button><button className="btn" onClick={async()=>{await api.patch(`/mentoring-sessions/${s._id}`,{status:'CANCELLED'});load()}}>Cancel</button></span>}</div>)}</div>{open && <div className="card"><h2 className="font-bold">Learner progress</h2>{open.progress.map(p => <p key={p.courseId}>{p.title}: {p.pct}%</p>)}<button className="btn mt-2" onClick={async () => { const note = prompt('Mentoring note'); if (note) { await api.post(`/mentor/learners/${open.studentId}/notes`, { note }); toast('Note saved'); } }}>Add note</button></div>}</div>;
}
